<script lang="ts">
	import { page } from '$app/state';
	import { DocsShell, DocsSeo, docsOgImagePath } from 'acrolls/docs';
	import type { DocsTocItem } from 'acrolls/docs';
	import { docs } from '../../lib/docs/source';
	import type { Snippet } from 'svelte';

	let { children }: { children: Snippet } = $props();

	// Derive the index check from the configured base href — never hardcode the route.
	const base = docs.nav.baseHref;
	const isIndex = $derived(page.url.pathname === base || page.url.pathname === `${base}/`);
	const currentDoc = $derived(docs.get(page.url.pathname));
	// Auto OG image for this page (generated by the /og endpoint).
	const ogImage = $derived(currentDoc ? docsOgImagePath(currentDoc) : docsOgImagePath('index'));
	// Honor frontmatter `search: { exclude: true }` — skip this page from the index.
	const searchable = $derived(
		!(currentDoc?.metadata?.search as { exclude?: boolean } | undefined)?.exclude
	);
	// Compile-time headings (from `metadata.headings`) render the TOC server-side — present for
	// crawlers and no-JS readers, with no post-mount DOM scan.
	const headings = $derived(currentDoc?.metadata?.headings as DocsTocItem[] | undefined);
</script>

<DocsSeo
	nav={docs.nav}
	pathname={page.url.pathname}
	document={currentDoc}
	{ogImage}
	site={{ twitter: '@acrolls', locale: 'en_US' }}
/>

<DocsShell
	nav={docs.nav}
	pathname={page.url.pathname}
	showToc={!isIndex}
	showPager={!isIndex}
	{headings}
	{searchable}
	siteName="Acrolls"
	githubUrl="https://github.com/fractalmandala/acrolls"
	showThemeToggle={false}
>
	{@render children()}
</DocsShell>
